FROM redis:7-alpine

# (Optional) Copy a custom configuration file
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Start redis with the custom config
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]