name: React Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run React Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout Respository
        uses: actions/checkout@v3

      - name: Setup Node.jobs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        working-directory: client
        run: npm install
      
      - name: Run Tests
        working-directory: client
        run: npm test -- --watchAll=false
